### PR TITLE
Code improvements

### PR DESCRIPTION
**Pull request by AlFasGD**
This aims to improve the code in various aspects, including readability, consistency, abstraction and elegance.

Regarding styles: there must either be a style ruleset. Since this is not my project, I won't be enforcing any styles, thus won't be making any changes to the code style that is inconsistently applied.

### CODE REVIEW

**Comment by nicolasdeory** [comment]
Thanks for the code improvements. There certainly is some housekeeping to be done.
If you're happy with the current commits, I'll merge them and you can make another pull request if you want to, with any other improvements.

**Comment by nicolasdeory** [comment]
I have updated the contributing file with some basic style guidelines. We'll be progressively be fixing style inconsistencies.

**Comment by AlFasGD** [comment]
You may merge the current changes, I'll be making another PR containing style maintenance. You may focus on more functional parts of the project.

**Comment by nicolasdeory** [comment]
Could you reopen the PR and merge to the dev branch? I'd like to keep master for releases only.

**Pull request merged**
